import { TaskType } from "../types/Task";

export const tasks: TaskType[] = [
  {
    id: "1",
    title: "Task 1",
    description: "This is a description for task 1",
    dueDate: new Date("2021-12-31"),
    completed: false,
  },
  {
    id: "2",
    title: "Task 2",
    description: "This is a description for task 2",
    dueDate: new Date("2021-12-31"),
    completed: false,
  },
  {
    id: "3",
    title: "Task 3",
    description: "This is a description for task 3",
    dueDate: new Date("2021-12-31"),
    completed: false,
  },
  // add more tasks below
  {
    id: "4",
    title: "Task 4",
    description: "This is a description for task 4",
    dueDate: new Date("2021-12-31"),
    completed: false,
  },
  {
    id: "5",
    title: "Task 5",
    description: "This is a description for task 5",
    dueDate: new Date("2021-12-31"),
    completed: false,
  },
  {
    id: "6",
    title: "Task 6",
    description: "This is a description for task 6",
    dueDate: new Date("2021-12-31"),
    completed: false,
  },
  {
    id: "7",
    title: "Task 7",
    description: "This is a description for task 7",
    dueDate: new Date("2021-12-31"),
    completed: false,
  },
  {
    id: "8",
    title: "Task 8",
    description: "This is a description for task 8",
    dueDate: new Date("2021-12-31"),
    completed: false,
  },
  {
    id: "9",
    title: "Task 9",
    description: "This is a description for task 9",
    dueDate: new Date("2021-12-31"),
    completed: false,
  },
  {
    id: "10",
    title: "Task 10",
    description: "This is a description for task 10",
    dueDate: new Date("2021-12-31"),
    completed: false,
  },
  {
    id: "11",
    title: "Task 11",
    description: "This is a description for task 11",
    dueDate: new Date("2021-12-31"),
    completed: false,
  },
  {
    id: "12",
    title: "Task 12",
    description: "This is a description for task 12",
    dueDate: new Date("2021-12-31"),
    completed: false,
  },
  {
    id: "13",
    title: "Task 13",
    description: "This is a description for task 13",
    dueDate: new Date("2021-12-31"),
    completed: false,
  },
  {
    id: "14",
    title: "Task 14",
    description: "This is a description for task 14",
    dueDate: new Date("2021-12-31"),
    completed: false,
  },
  {
    id: "15",
    title: "Task 15",
    description: "This is a description for task 15",
    dueDate: new Date("2021-12-31"),
    completed: false,
  },
  {
    id: "16",
    title: "Task 16",
    description: "This is a description for task 16",
    dueDate: new Date("2021-12-31"),
    completed: false,
  },
  {
    id: "17",
    title: "Task 17",
    description: "This is a description for task 17",
    dueDate: new Date("2021-12-31"),
    completed: false,
  },
  {
    id: "18",
    title: "Task 18",
    description: "This is a description for task 18",
    dueDate: new Date("2021-12-31"),
    completed: false,
  },
  {
    id: "19",
    title: "Task 19",
    description: "This is a description for task 19",
    dueDate: new Date("2021-12-31"),
    completed: false,
  },
  {
    id: "20",
    title: "Task 20",
    description: "This is a description for task 20",
    dueDate: new Date("2021-12-31"),
    completed: false,
  },
];
